### ISSUE TITLE
Invalid config for [group]: [module] is an invalid option for [group]

### ISSUE THREAD

**Issue by kesm** [so3n/Bring-Back-group.all_x#3]
Hi, 

I'm trying to have bbgax working but it keeps saying that I have a problem in my config : 
I installed bbgax via hacs, here is my appdaemon folder
![image](https://user-images.githubusercontent.com/6907912/93347760-bd3bf600-f835-11ea-82bc-3ae22fb058ad.png)

My configuration.yaml is configured like this : 
`group: !include groups.yaml`

and this is what I put on the top of my groups.yaml 
```
any_name_you_wish:
  module: bbgax
  class: group_all_x
  domains: 
    - device_tracker
    - light
    - switch
````

but HA says that I have a problem with my config : 
`Invalid config for [group]: [module] is an invalid option for [group]. Check: group->group->any_name_you_wish->module. (See /config/configuration.yaml, line 25).`

Did I put my config in the wrong yaml?

**Comment by nickneos** [comment]
Under apps folder in appdaemon create a file called `apps.yaml` (can be named anything as long as its a yaml file) and paste this in there:

```yaml
any_name_you_wish:
  module: bbgax
  class: group_all_x
  domains: 
    - device_tracker
    - light
    - switch
```

Keep your `groups.yaml` file but delete the contents in there (ie. leave it empty)

**Comment by kesm** [comment]
Hum that's strange, here is my config:

configuration.yaml 
```
hacs:
  token: !secret hacs
  appdaemon: true  
```
/appdaemon/apps/app.yaml
```
media_players:
  module: bbgax
  class: group_all_x
  domains: 
    - media_player
```

and groups.yaml is here but empty

I restarted HA but I can't find media_players group in developper tools, I guess I'm still missing something but didn't find any logs
